Logistics.WebAppAdmin/Areas/ClientApp/Controllers/OrderClientController.cs
using Logistics.Data.DTO.Order;
using Logistics.Data.Entities;
using Logistics.Service.Interfaces;
using Logistics.WebAppAdmin.Controllers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using QuanLySinhVien.WebApp.Commons;
using System;
using System.Threading.Tasks;

namespace Logistics.WebAppAdmin.Areas.ClientApp.Controllers
{
    [Area("ClientApp")]
    public class OrderClientController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IOrderDetailService _orderDetailService;

        public OrderClientController(ILogger<OrderController> logger, IOrderService orderService, IOrderDetailService orderDetailService)
        {
            _orderService = orderService;
            _orderDetailService = orderDetailService;
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetOrders(string body)
        {
            OrderSearchDTO model = JsonConvert.DeserializeObject<OrderSearchDTO>(body);

            var results = await _orderService.GetOrders(model);

            if (results.Capacity > 0)
            {
                ApiResult<OrderGridPagingDTO<Order>> result = new ApiResult<OrderGridPagingDTO<Order>>();
                OrderGridPagingDTO<Order> resultPaging = new OrderGridPagingDTO<Order>()
                {
                    Items = results,
                    PageIndex = results.PageIndex,
                    PageSize = results.Capacity,
                    TotalPages = results.TotalPages
                };
                var a = results.PageIndex;
                result.Message = "";
                result.ResultObj = resultPaging;
                result.statusCode = 200;
                return Json(result);
            }
            else
            {
                ApiResult<string> result = new ApiResult<string>();
                result.Message = "No data.";
                result.ResultObj = "";
                result.statusCode = 200;
                return Json(result);
            }
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Add(string body)
        {
            OrderCreateDTO model = JsonConvert.DeserializeObject<OrderCreateDTO>(body);
            if (model != null)
            {
                ApiResult<bool> result = new ApiResult<bool>();
                OrderCreateDTO order = new OrderCreateDTO()
                {
                    OrderId = model.OrderId,
                    Status = model.Status,
                    CustomerAddress = model.CustomerAddress,
                    CustomerEmail = model.CustomerEmail,
                    CustomerName = model.CustomerName,
                    CustomerPhone = model.CustomerPhone,
                    DeliveryAddress = model.DeliveryAddress,
                    DeliveryDate = model.DeliveryDate,
                    EstimateDeliveryDate = DateTime.Now.AddDays(3),
                    CreatedDate = DateTime.Now,
                    UpdatedDate = DateTime.Now
                };

                var isSuccess = _orderService.CreateOrder(order);
                if(isSuccess)
                {
                    foreach (var item in model.OrderItems)
                    {
                        isSuccess = _orderDetailService.CreateOrderDetail(item);
                    }
                }
                if (isSuccess)
                {
                    result.Message = "Create successfully.";
                    result.ResultObj = true;
                    result.statusCode = 200;
                    return Json(result);
                }
                else
                {
                    result.Message = "Create order fail. Please try again.";
                    result.ResultObj = false;
                    result.statusCode = 200;
                    return Json(result);
                }
            }
            else
            {
                ApiResult<bool> result = new ApiResult<bool>();
                result.Message = "Some error. Please try again serviral minutes.";
                result.ResultObj = false;
                result.statusCode = 200;
                return Json(result);
            }
        }

        public IActionResult Detail(string id)
        {
            var order = _orderService.GetOrderDTOById(id);
            return View(order);
        }
    }
}

Logistics.WebAppAdmin/Areas/ClientApp/Views/OrderClient/Detail.cshtml
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

@section Scripts
    {
    <script src="~/assets/js/notification.js"></script>
    <script>
        Init();

        function Init() {
            console.log(1);
            InitDatetimePicker();
        }

        function InitDatetimePicker() {
            $("#delivery_date").datepicker();
            $("#estimate_delivery_date").datepicker();
        }


        function UpdateOrder(id) {
            var email = document.getElementById('email').value;
            var name = document.getElementById('name').value;
            var fullname = document.getElementById('name').value;
            var address = document.getElementById('address').value;
            var phone = document.getElementById('phone').value;
            var delivery_date = document.getElementById('delivery_date').value;
            var estimate_delivery_date = document.getElementById('estimate_delivery_date').value;
            var status = document.getElementById('status').checked;
            var delivery_address = document.getElementById('delivery_address').value;

            var order = new Object();
            order.id = id;
            order.customeremail = email;
            order.customername = name;
            order.customeraddress = address;
            order.customerphone = phone;
            order.deliverydate = delivery_date;
            order.estimatedeliverydate = estimate_delivery_date;
            order.status = status;
            order.deliveryaddress = delivery_address;
            console.log(order);
            $.ajax({
                type: 'POST',
                url: 'https://localhost:44358/Order/UpdateOrder',
                dataType: 'json',
                data: { body: JSON.stringify(order) },
                success: function (data) {
                    console.log(data);
                    if (data.resultObj == true) {
                        CreateNotification(data.message, "success");
                        window.location.href = "https://localhost:44358/Order/Index";
                    }
                    else {
                        CreateNotification(data.message, "error");
                    }
                },
                error: function (emp) {
                    alert('error');
                }
            })
        }
    </script>
}


<div id="container"></div>

<div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
     data-sidebar-position="fixed" data-header-position="fixed">
    <!--  Main wrapper -->
    <div class="body-wrapper">
        <!--  Header Start -->
        <partial name="_Header" />
        <!--  Header End -->
        <div class="container-fluid">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">Update order</h5>
                    <div class="card">
                        <div class="card-body">
                            <form>
                                <div class="mb-3">
                                    <label class="form-label">Order Id</label>
                                    <input type="text" class="form-control" disabled value="@Model.Id" id="identity">
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Customer Email</label>
                                    <input type="text" class="form-control" value="@Model.CustomerEmail" id="email">
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Customer Name</label>
                                    <input type="text" class="form-control" value="@Model.CustomerName" id="name">
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Customer Address</label>
                                    <input type="text" class="form-control" value="@Model.CustomerAddress" id="address">
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Customer Phone</label>
                                    <input type="text" class="form-control" value="@Model.CustomerPhone" id="phone">
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Delivery Date</label>
                                    <input id="delivery_date" type="text" value="@Model.DeliveryDate" class="form-control" />
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Estimate Delivery Date</label>
                                    <input id="estimate_delivery_date" type="text" value="@Model.EstimateDeliveryDate" class="form-control" />
                                </div>
                                <div class="mb-3">
                                    <input type="checkbox" class="form-check-input" checked="@Model.Status" id="status">
                                    <label class="form-check-label" for="exampleCheck1">Status Delivered</label>
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Delivery Address</label>
                                    <input type="text" class="form-control" value="@Model.DeliveryAddress" id="delivery_address">
                                </div>
                                <div class="mb-3">
                                    <label class="form-label">Products</label>
                                    <div class="table-responsive">
                                        <table class="table text-nowrap mb-0 align-middle">
                                            <thead class="text-dark fs-4">
                                                <tr>
                                                    <th class="border-bottom-0">
                                                        <h6 class="fw-semibold mb-0">OrderId</h6>
                                                    </th>
                                                    <th class="border-bottom-0">
                                                        <h6 class="fw-semibold mb-0">ProductId</h6>
                                                    </th>
                                                    <th class="border-bottom-0">
                                                        <h6 class="fw-semibold mb-0">Name</h6>
                                                    </th>
                                                    <th class="border-bottom-0">
                                                        <h6 class="fw-semibold mb-0">TotalPrice</h6>
                                                    </th>
                                                    <th class="border-bottom-0">
                                                        <h6 class="fw-semibold mb-0">Quantity</h6>
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model.OrderItems)
                                                {
                                                    <tr>
                                                        <td class="border-bottom-0">
                                                            <span class="fw-normal">@item.OrderId</span>
                                                        </td>
                                                        <td class="border-bottom-0">
                                                            <p class="mb-0 fw-normal">@item.ProductId</p>
                                                        </td>
                                                        <td class="border-bottom-0">
                                                            <h6 class="fw-semibold mb-0 fs-4">@item.ProductName</h6>
                                                        </td>
                                                        <td class="border-bottom-0">
                                                            <h6 class="fw-semibold mb-0 fs-4">@item.TotalPrice</h6>
                                                        </td>
                                                        <td class="border-bottom-0">
                                                            <h6 class="fw-semibold mb-0 fs-4">@item.Quantity</h6>
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                @Html.ActionLink("Back", "Index", "OrderClient", new { area = "ClientApp" }, new { @class = "btn btn-outline-primary mx-3 mt-2" })
                            </form>
                        </div>
                    </div>
                    <div id="container"></div>
                </div>
            </div>
        </div>
    </div>
</div>

Logistics.WebAppAdmin/Areas/ClientApp/Views/OrderClient/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

@section Scripts
    {
    <script src="~/assets/js/notification.js"></script>
    <script>
        Init();

        function Init() {
            console.log(1);
            InitDatetimePicker();
            GetOrderUsingAjax(1);
        }

        function InitDatetimePicker() {
            $("#datepicker_start").datepicker();
            $("#datepicker_end").datepicker();
        }

        function GetOrderUsingAjax(pageNum, pageSize) {
            $("#paged").empty();
            var OrderSearch = new Object();
            var searchValue = document.getElementById('search_value');
            var datepickerStart = document.getElementById('datepicker_start');
            var datepickerEnd = document.getElementById('datepicker_end');

            OrderSearch.SearchValue = null;
            OrderSearch.DateStart = null;
            OrderSearch.DateEnd = null;
            OrderSearch.PageIndex = pageNum;
            OrderSearch.PageNumber = 2;


            if (searchValue.value != null && searchValue.value != "") {
                OrderSearch.SearchValue = searchValue.value;
            }
            if (datepickerStart.value != null && datepickerStart.value != "") {
                OrderSearch.DateStart = datepickerStart.value;
            }
            if (datepickerEnd.value != null && datepickerEnd.value != "") {
                OrderSearch.DateEnd = datepickerEnd.value;
            }
            $.ajax({
                type: 'GET',
                url: 'https://localhost:44358/ClientApp/OrderClient/GetOrders',
                dataType: 'json',
                data: { body: JSON.stringify(OrderSearch) },
                success: function (data) {
                    console.log(data.resultObj);
                    $('#tblorders tbody > tr').remove();
                    if (data.resultObj.items != null) {
                        var rows;
                        $.each(data.resultObj.items, function (i, item) {
                            let btnCart = "";
                            if (item.status) {
                                btnCart = btnCart + "<span class='badge bg-danger rounded-3 fw-semibold'>Delivered</span>";;
                            }
                            else {
                                btnCart = btnCart + "<span class='badge bg-success rounded-3 fw-semibold'>Not Delivery</span>";
                            }
                            rows += "<tr>"
                                + "<td>" + item.id + "</td>"
                                + "<td>" + item.customerEmail + "</td>"
                                + "<td>" + item.customerName + "</td>"
                                + "<td>" + item.customerPhone + "</td>"
                                + "<td>" + item.deliveryAddress + "</td>"
                                + "<td>" + item.deliveryDate + "</td>"
                                + "<td>" + item.estimateDeliveryDate + "</td>"
                                + "<td>" + btnCart + "</td>"
                                + "<td> <a class='btn btn-warning' href='/ClientApp/OrderClient/Detail/" + item.id + "'><i class='ti ti-edit'></i></a></td>"
                                + "</tr>";
                            ;
                        });
                        $('#tblorders tbody').append(rows);
                        PaggingTemplate(data.resultObj.totalPages, data.resultObj.pageIndex);
                    }
                },
                error: function (emp) {
                    alert('error');
                }
            });
        }

        function PaggingTemplate(totalPage, currentPage) {
            console.log(totalPage);
            console.log(currentPage);
            var template = "";
            var TotalPages = totalPage;
            var CurrentPage = currentPage;
            var PageNumberArray = Array();


            var countIncr = 1;
            for (var i = currentPage; i <= totalPage; i++) {
                PageNumberArray[0] = currentPage;
                if (totalPage != currentPage && PageNumberArray[countIncr - 1] != totalPage) {
                    PageNumberArray[countIncr] = i + 1;
                }
                countIncr++;
            };
            PageNumberArray = PageNumberArray.slice(0, 5);
            var FirstPage = 1;
            var LastPage = totalPage;
            if (totalPage != currentPage) {
                var ForwardOne = currentPage + 1;
            }
            var BackwardOne = 1;
            if (currentPage > 1) {
                BackwardOne = currentPage - 1;
            }

            template = "<p>" + CurrentPage + " of " + TotalPages + " pages</p>"
            template = template + '<ul class="pagination">' +
                '<li class="previous"><a href="#" onclick="GetOrderUsingAjax(' + FirstPage + ')"><i class="ti ti-arrow-big-left-filled"></i>&nbsp;First</a></li>' +
                '<li><a href="#" onclick="GetOrderUsingAjax(' + BackwardOne + ')"><<</a>';

            var numberingLoop = "";
            for (var i = 0; i < PageNumberArray.length; i++) {
                numberingLoop = numberingLoop + '<a class="page-number active" onclick="GetOrderUsingAjax(' + PageNumberArray[i] + ')" href="#">' + PageNumberArray[i] + ' &nbsp;&nbsp;</a>'
            }
            template = template + numberingLoop + '<a href="#" onclick="GetOrderUsingAjax(' + ForwardOne + ')" >>></a></li>' +
                '<li class="next"><a href="#" onclick="GetOrderUsingAjax(' + LastPage + ')">Last&nbsp;<i class="ti ti-arrow-big-right-filled"></i></a></li></ul>';
            $("#paged").append(template);

        }

        function UpdateStatus(id) {
            console.log(id);
            $.ajax({
                type: 'POST',
                url: 'https://localhost:44358/Order/UpdateStatus',
                dataType: 'json',
                data: { id: id },
                success: function (data) {
                    console.log(data);
                    if (data.resultObj == true) {
                        CreateNotification(data.message, "success");
                        GetOrderUsingAjax(1);
                    }
                    else {
                        CreateNotification(data.message, "error");
                    }
                },
                error: function (emp) {
                    alert('error');
                }
            })
        }
    </script>
}

<style>
    #container {
        position: fixed;
        bottom: 10px;
        right: 10px;
    }
</style>
<div id="container"></div>
<div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
     data-sidebar-position="fixed" data-header-position="fixed">
    <!--  Main wrapper -->
    <div class="body-wrapper">
        <!--  Header Start -->
        <header class="app-header">
            <nav class="navbar navbar-expand-lg navbar-light">
                <ul class="navbar-nav">
                    <li class="nav-item d-block d-xl-none">
                        <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                            <i class="ti ti-menu-2"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                            <i class="ti ti-bell-ringing"></i>
                            <div class="notification bg-primary rounded-circle"></div>
                        </a>
                    </li>
                </ul>
                <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
                    <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">

                        @*<a href="https://localhost:44386/Home/Logout" class="btn btn-primary">Thoát</a>*@
                        <li class="nav-item dropdown">
                            <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                <img src="../../assets/images/profile/user-1.jpg" alt="" width="35" height="35" class="rounded-circle">
                            </a>
                            <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                                <div class="message-body">
                                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                        <i class="ti ti-user fs-6"></i>
                                        <p class="mb-0 fs-3">My Profile</p>
                                    </a>
                                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                        <i class="ti ti-mail fs-6"></i>
                                        <p class="mb-0 fs-3">My Account</p>
                                    </a>
                                    <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                        <i class="ti ti-list-check fs-6"></i>
                                        <p class="mb-0 fs-3">My Task</p>
                                    </a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!--  Header End -->
        <div>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title fw-semibold mb-4">List Order</h5>
                    <form>
                        <div class="form-actions no-color">
                            <p>
                                <div class="row">
                                    <div class="col-lg-4 d-flex align-items-strech">
                                        <input type="text" id="search_value" class="form-control" placeholder="Search for name and order id" />
                                    </div>
                                    <div class="col-lg-3 d-flex align-items-strech">
                                        <input id="datepicker_start" type="text" placeholder="Start Date" class="form-control" />
                                    </div>
                                    <div class="col-lg-3 d-flex align-items-strech">
                                        <input id="datepicker_end" type="text" placeholder="End Date" class="form-control" />
                                    </div>
                                    <div class="col-lg-2">
                                        <input type="button" value="Search" class="btn btn-primary" onclick="GetOrderUsingAjax()" />
                                        @Html.ActionLink("Add", "Add", "OrderClient", new { area = "ClientApp" }, new { @class = "btn btn-success" })
                                    </div>
                                </div>
                            </p>
                        </div>
                    </form>
                    <div class="col-lg-12 d-flex align-items-stretch">
                        <div class="card w-100">
                            <div class="card-body p-4">
                                <div class="table-responsive">
                                    <table class="table text-nowrap mb-0 align-middle" id="tblorders">
                                        <thead class="text-dark fs-4">
                                            <tr>
                                                <th class="border-bottom-0">
                                                    <h6 class="fw-semibold mb-0">Product Id</h6>
                                                </th>
                                                <th class="border-bottom-0">
                                                    <h6 class="fw-semibold mb-0">Product Name</h6>
                                                </th>
                                                <th class="border-bottom-0">
                                                    <h6 class="fw-semibold mb-0">TotalPrice</h6>
                                                </th>
                                                <th class="border-bottom-0">
                                                    <h6 class="fw-semibold mb-0">Quantity</h6>
                                                </th>
                                                <th class="border-bottom-0">
                                                    <h6 class="fw-semibold mb-0">Add</h6>
                                                </th>
                                                <th class="border-bottom-0 text-center">
                                                    <h6 class="fw-semibold mb-0">###</h6>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                           
                                        </tbody>
                                    </table>
                                </div>
                                <div style="margin-top:10px">
                                    <nav aria-label="Page navigation example" id="paged">

                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>